### ISSUE TITLE
Timetable issue

### ISSUE THREAD

**Issue by SK1990101** [vcs-asia/ICMS.EMS.User#2] opened 2024-01-12 01:11 UTC
Hi, timetable uploaded unable to preview new timetable uploaded and previous timetable uploaded not able to preview when click on "Details" icon. Attached screenshot for your reference.

![Untitled](https://github.com/vcs-asia/ICMS.EMS.User/assets/156168966/ed50c6a3-91d6-410c-b7bd-a7d14d5db4af)

**Comment by SK1990101** [comment] 2024-01-12 09:56
Apologies for bothering, just checking is there any update on this.

**Comment by vjbollavarapu** [comment] 2024-01-14 06:47
Please allow me until Monday I will get it done.

**Comment by SK1990101** [comment] 2024-01-14 15:26
Ok Vijay, noted with thanks.

**Comment by SK1990101** [comment] 2024-01-15 04:07
Hi Vijay, any updates....

**Comment by vjbollavarapu** [comment] 2024-01-15 15:37
Please find the below screenshots

![image](https://github.com/vcs-asia/ICMS.EMS.User/assets/16207415/dbf3f28a-7b68-4f1c-b3d2-175e98ec4039)

![image](https://github.com/vcs-asia/ICMS.EMS.User/assets/16207415/bcde435c-a53c-4c55-892d-b87c82709323)

The issue is solved and to tested and confirmed.

**Comment by SK1990101** [comment] 2024-01-15 23:58
ok Vijay, thanks. Please let me confirm and then we can close this case. by 1pm today.

**Comment by SK1990101** [comment] 2024-01-19 01:06
Hi Vijay, sorry for delay informing. You may close this case. Thanks

**Comment by vjbollavarapu** [comment] 2024-01-19 05:58
Only the author can close this. Please close this by your end. TQ

**Closed** 2024-01-20 03:16 UTC
